### ISSUE TITLE
Enforce type checking of repository methods arguments

### ISSUE THREAD

**Issue by eltharim** [Hypothesize/storage.js#2]
For the moment, the repository io methods (saveAsync, getAsync...) do not check for the type of the objects passed ("saveAsync(obj)" would accept any value as "obj", for instance)

We should ensure each repository io method checks the type of its arguments.

Also, find a way to pass the entities to it in the form of a structure, not strings

**Comment by agyemanjp** [comment]
Implemented by commits from @agyemanjp
