### ISSUE TITLE
Update tooling and project structure

### ISSUE THREAD

**Issue by eltharim** [Hypothesize/storage.js#20]
- Use just one single _tsconfig_ file by compiling from /_src_ and flattening after compilation
- Add/Use standard eslint rules/ignore file 
- Put test .ts files (one per each source file) in separate folder /_test_
- Add /_dist_ folder to repository (by commenting it out from ._gitignore_), until we publish on NPM
- Use "files" property in _package.json_ to indicate which files are published as part of the package; don't use ._npmignore_
- Remove the "declaration: true" property from package.json
- Add standard base dependencies:
```
npm install --save-dev \
	@types/node \
	mocha @types/mocha \
	source-map-support @types/source-map-support \
	eslint @types/eslint \
	@typescript-eslint/parser \
	@typescript-eslint/eslint-plugin \
	eslint-plugin-fp \
	@hutsoninc/flatten-dir-cli \
	typescript
```

- Use standard scripts as shown below: 
```
"scripts": {
		"setup": "rm -rf ./node_modules package-lock.json && npm install",
		"clean": "rm -rf dist .eslintcache *-report.json",
		"lint": "eslint --ext ts,tsx --output-file lint-report.json --format dist/eslint-formatter.js --cache src/*",
		"build": "tsc && flatten dist && rm -rf dist/*.test.js.map dist/*.test.d.ts",
		"test": "mocha dist/*.test.js --reporter dist/mocha-reporter.js >| test-report.json",
		"ci": "npm run lint && npm run build && npm run test"
}
```

**Comment by agyemanjp** [comment]
Implemented by various commits
