### ISSUE TITLE
Update repository types

### ISSUE THREAD

**Issue by eltharim** [Hypothesize/storage.js#23]
The names should be "RepositoryReadOnly", "RepositoryWritable" (with save), "RepositoryLinker" and just "Repository".

The linker repository type will have to be added, as follow:
```
export interface RepositoryLinker<E1 extends keyof DTOsMap, E2 extends keyof DTOsMap> {
    linkAsync: (obj: ToStore<E>) => Promise<FromStore<E>>
    unlinkAsync: (obj: ToStore<E>) => Promise<FromStore<E>>
}
```

**Comment by agyemanjp** [comment]
No longer valid
