### ISSUE TITLE
Return a clean error when an entity saving fails

### ISSUE THREAD

**Issue by eltharim** [Hypothesize/storage.js#35]
Currently, when an insertion/update fail and the returned object is empty, or has all properties set to undefined, the cache bustnig operation throws an error.

It's because the absence of a parentId makes this line fail:
`result.id !== undefined ? this.bustCache(dto.name, { type: "single", entityId: result.id }) : undefined;`

We should instead verify the returned object (after the save), and if it doesn't have a parentId, send a clean error message.

**Comment by agyemanjp** [comment]
No longer valid
